apiVersion: v1
items:
- apiVersion: v1
  kind: Node
  metadata:
    annotations:
      alpha.kubernetes.io/provided-node-ip: 10.146.0.55
      flannel.alpha.coreos.com/backend-data: '{"VNI":1,"VtepMAC":"6e:9a:3e:a8:c7:7d"}'
      flannel.alpha.coreos.com/backend-type: vxlan
      flannel.alpha.coreos.com/kube-subnet-manager: "true"
      flannel.alpha.coreos.com/public-ip: 10.146.0.55
      k3s.io/hostname: ai-lab-a100-2
      k3s.io/internal-ip: 10.146.0.55
      k3s.io/node-args: '["server","--node-name","ai-lab-a100-2"]'
      k3s.io/node-config-hash: D2AH7V4NLZL4YZ4PDS255MOJDJ3WFQVXPIVUOUGXMIQB2XBZRTQQ====
      k3s.io/node-env: '{}'
      nfd.node.kubernetes.io/feature-labels: cpu-cpuid.ADX,cpu-cpuid.AESNI,cpu-cpuid.AVX,cpu-cpuid.AVX2,cpu-cpuid.AVX512BW,cpu-cpuid.AVX512CD,cpu-cpuid.AVX512DQ,cpu-cpuid.AVX512F,cpu-cpuid.AVX512VL,cpu-cpuid.AVX512VNNI,cpu-cpuid.CMPXCHG8,cpu-cpuid.FMA3,cpu-cpuid.FXSR,cpu-cpuid.FXSROPT,cpu-cpuid.HLE,cpu-cpuid.HYPERVISOR,cpu-cpuid.IA32_ARCH_CAP,cpu-cpuid.IBPB,cpu-cpuid.LAHF,cpu-cpuid.MD_CLEAR,cpu-cpuid.MOVBE,cpu-cpuid.MPX,cpu-cpuid.OSXSAVE,cpu-cpuid.RTM,cpu-cpuid.SPEC_CTRL_SSBD,cpu-cpuid.STIBP,cpu-cpuid.SYSCALL,cpu-cpuid.SYSEE,cpu-cpuid.X87,cpu-cpuid.XGETBV1,cpu-cpuid.XSAVE,cpu-cpuid.XSAVEC,cpu-cpuid.XSAVEOPT,cpu-cpuid.XSAVES,cpu-hardware_multithreading,cpu-model.family,cpu-model.id,cpu-model.vendor_id,kernel-config.NO_HZ,kernel-config.NO_HZ_FULL,kernel-version.full,kernel-version.major,kernel-version.minor,kernel-version.revision,nvidia.com/cuda.driver-version.full,nvidia.com/cuda.driver-version.major,nvidia.com/cuda.driver-version.minor,nvidia.com/cuda.driver-version.revision,nvidia.com/cuda.driver.major,nvidia.com/cuda.driver.minor,nvidia.com/cuda.driver.rev,nvidia.com/cuda.runtime-version.full,nvidia.com/cuda.runtime-version.major,nvidia.com/cuda.runtime-version.minor,nvidia.com/cuda.runtime.major,nvidia.com/cuda.runtime.minor,nvidia.com/gfd.timestamp,nvidia.com/gpu.compute.major,nvidia.com/gpu.compute.minor,nvidia.com/gpu.count,nvidia.com/gpu.family,nvidia.com/gpu.machine,nvidia.com/gpu.memory,nvidia.com/gpu.mode,nvidia.com/gpu.product,nvidia.com/gpu.replicas,nvidia.com/gpu.sharing-strategy,nvidia.com/mig-1g.5gb.count,nvidia.com/mig-1g.5gb.engines.copy,nvidia.com/mig-1g.5gb.engines.decoder,nvidia.com/mig-1g.5gb.engines.encoder,nvidia.com/mig-1g.5gb.engines.jpeg,nvidia.com/mig-1g.5gb.engines.ofa,nvidia.com/mig-1g.5gb.memory,nvidia.com/mig-1g.5gb.multiprocessors,nvidia.com/mig-1g.5gb.product,nvidia.com/mig-1g.5gb.replicas,nvidia.com/mig-1g.5gb.sharing-strategy,nvidia.com/mig-1g.5gb.slices.ci,nvidia.com/mig-1g.5gb.slices.gi,nvidia.com/mig-2g.10gb.count,nvidia.com/mig-2g.10gb.engines.copy,nvidia.com/mig-2g.10gb.engines.decoder,nvidia.com/mig-2g.10gb.engines.encoder,nvidia.com/mig-2g.10gb.engines.jpeg,nvidia.com/mig-2g.10gb.engines.ofa,nvidia.com/mig-2g.10gb.memory,nvidia.com/mig-2g.10gb.multiprocessors,nvidia.com/mig-2g.10gb.product,nvidia.com/mig-2g.10gb.replicas,nvidia.com/mig-2g.10gb.sharing-strategy,nvidia.com/mig-2g.10gb.slices.ci,nvidia.com/mig-2g.10gb.slices.gi,nvidia.com/mig-3g.20gb.count,nvidia.com/mig-3g.20gb.engines.copy,nvidia.com/mig-3g.20gb.engines.decoder,nvidia.com/mig-3g.20gb.engines.encoder,nvidia.com/mig-3g.20gb.engines.jpeg,nvidia.com/mig-3g.20gb.engines.ofa,nvidia.com/mig-3g.20gb.memory,nvidia.com/mig-3g.20gb.multiprocessors,nvidia.com/mig-3g.20gb.product,nvidia.com/mig-3g.20gb.replicas,nvidia.com/mig-3g.20gb.sharing-strategy,nvidia.com/mig-3g.20gb.slices.ci,nvidia.com/mig-3g.20gb.slices.gi,nvidia.com/mig.capable,nvidia.com/mig.strategy,nvidia.com/mps.capable,nvidia.com/vgpu.present,pci-10de.present,pci-1af4.present,storage-nonrotationaldisk,system-os_release.ID,system-os_release.VERSION_ID,system-os_release.VERSION_ID.major,system-os_release.VERSION_ID.minor
      node.alpha.kubernetes.io/ttl: "0"
      volumes.kubernetes.io/controller-managed-attach-detach: "true"
    creationTimestamp: "2026-04-23T08:33:09Z"
    finalizers:
    - wrangler.cattle.io/node
    labels:
      beta.kubernetes.io/arch: amd64
      beta.kubernetes.io/instance-type: k3s
      beta.kubernetes.io/os: linux
      feature.node.kubernetes.io/cpu-cpuid.ADX: "true"
      feature.node.kubernetes.io/cpu-cpuid.AESNI: "true"
      feature.node.kubernetes.io/cpu-cpuid.AVX: "true"
      feature.node.kubernetes.io/cpu-cpuid.AVX2: "true"
      feature.node.kubernetes.io/cpu-cpuid.AVX512BW: "true"
      feature.node.kubernetes.io/cpu-cpuid.AVX512CD: "true"
      feature.node.kubernetes.io/cpu-cpuid.AVX512DQ: "true"
      feature.node.kubernetes.io/cpu-cpuid.AVX512F: "true"
      feature.node.kubernetes.io/cpu-cpuid.AVX512VL: "true"
      feature.node.kubernetes.io/cpu-cpuid.AVX512VNNI: "true"
      feature.node.kubernetes.io/cpu-cpuid.CMPXCHG8: "true"
      feature.node.kubernetes.io/cpu-cpuid.FMA3: "true"
      feature.node.kubernetes.io/cpu-cpuid.FXSR: "true"
      feature.node.kubernetes.io/cpu-cpuid.FXSROPT: "true"
      feature.node.kubernetes.io/cpu-cpuid.HLE: "true"
      feature.node.kubernetes.io/cpu-cpuid.HYPERVISOR: "true"
      feature.node.kubernetes.io/cpu-cpuid.IA32_ARCH_CAP: "true"
      feature.node.kubernetes.io/cpu-cpuid.IBPB: "true"
      feature.node.kubernetes.io/cpu-cpuid.LAHF: "true"
      feature.node.kubernetes.io/cpu-cpuid.MD_CLEAR: "true"
      feature.node.kubernetes.io/cpu-cpuid.MOVBE: "true"
      feature.node.kubernetes.io/cpu-cpuid.MPX: "true"
      feature.node.kubernetes.io/cpu-cpuid.OSXSAVE: "true"
      feature.node.kubernetes.io/cpu-cpuid.RTM: "true"
      feature.node.kubernetes.io/cpu-cpuid.SPEC_CTRL_SSBD: "true"
      feature.node.kubernetes.io/cpu-cpuid.STIBP: "true"
      feature.node.kubernetes.io/cpu-cpuid.SYSCALL: "true"
      feature.node.kubernetes.io/cpu-cpuid.SYSEE: "true"
      feature.node.kubernetes.io/cpu-cpuid.X87: "true"
      feature.node.kubernetes.io/cpu-cpuid.XGETBV1: "true"
      feature.node.kubernetes.io/cpu-cpuid.XSAVE: "true"
      feature.node.kubernetes.io/cpu-cpuid.XSAVEC: "true"
      feature.node.kubernetes.io/cpu-cpuid.XSAVEOPT: "true"
      feature.node.kubernetes.io/cpu-cpuid.XSAVES: "true"
      feature.node.kubernetes.io/cpu-hardware_multithreading: "true"
      feature.node.kubernetes.io/cpu-model.family: "6"
      feature.node.kubernetes.io/cpu-model.id: "85"
      feature.node.kubernetes.io/cpu-model.vendor_id: Intel
      feature.node.kubernetes.io/kernel-config.NO_HZ: "true"
      feature.node.kubernetes.io/kernel-config.NO_HZ_FULL: "true"
      feature.node.kubernetes.io/kernel-version.full: 6.17.0-1012-gcp
      feature.node.kubernetes.io/kernel-version.major: "6"
      feature.node.kubernetes.io/kernel-version.minor: "17"
      feature.node.kubernetes.io/kernel-version.revision: "0"
      feature.node.kubernetes.io/pci-10de.present: "true"
      feature.node.kubernetes.io/pci-1af4.present: "true"
      feature.node.kubernetes.io/storage-nonrotationaldisk: "true"
      feature.node.kubernetes.io/system-os_release.ID: ubuntu
      feature.node.kubernetes.io/system-os_release.VERSION_ID: "24.04"
      feature.node.kubernetes.io/system-os_release.VERSION_ID.major: "24"
      feature.node.kubernetes.io/system-os_release.VERSION_ID.minor: "04"
      kubernetes.io/arch: amd64
      kubernetes.io/hostname: ai-lab-a100-2
      kubernetes.io/os: linux
      node-role.kubernetes.io/control-plane: "true"
      node.kubernetes.io/instance-type: k3s
      nvidia.com/cuda.driver-version.full: 590.48.01
      nvidia.com/cuda.driver-version.major: "590"
      nvidia.com/cuda.driver-version.minor: "48"
      nvidia.com/cuda.driver-version.revision: "01"
      nvidia.com/cuda.driver.major: "590"
      nvidia.com/cuda.driver.minor: "48"
      nvidia.com/cuda.driver.rev: "01"
      nvidia.com/cuda.runtime-version.full: "13.1"
      nvidia.com/cuda.runtime-version.major: "13"
      nvidia.com/cuda.runtime-version.minor: "1"
      nvidia.com/cuda.runtime.major: "13"
      nvidia.com/cuda.runtime.minor: "1"
      nvidia.com/dra-kubelet-plugin: "true"
      nvidia.com/gfd.timestamp: "1776937988"
      nvidia.com/gpu.compute.major: "8"
      nvidia.com/gpu.compute.minor: "0"
      nvidia.com/gpu.count: "1"
      nvidia.com/gpu.deploy.container-toolkit: "true"
      nvidia.com/gpu.deploy.dcgm: "true"
      nvidia.com/gpu.deploy.dcgm-exporter: "true"
      nvidia.com/gpu.deploy.device-plugin: "true"
      nvidia.com/gpu.deploy.driver: "true"
      nvidia.com/gpu.deploy.gpu-feature-discovery: "true"
      nvidia.com/gpu.deploy.mig-manager: "true"
      nvidia.com/gpu.deploy.node-status-exporter: "true"
      nvidia.com/gpu.deploy.nvsm: "true"
      nvidia.com/gpu.deploy.operator-validator: "true"
      nvidia.com/gpu.family: ampere
      nvidia.com/gpu.machine: Google-Compute-Engine
      nvidia.com/gpu.memory: "40960"
      nvidia.com/gpu.mode: compute
      nvidia.com/gpu.present: "true"
      nvidia.com/gpu.product: NVIDIA-A100-SXM4-40GB
      nvidia.com/gpu.replicas: "0"
      nvidia.com/gpu.sharing-strategy: none
      nvidia.com/mig-1g.5gb.count: "2"
      nvidia.com/mig-1g.5gb.engines.copy: "1"
      nvidia.com/mig-1g.5gb.engines.decoder: "0"
      nvidia.com/mig-1g.5gb.engines.encoder: "0"
      nvidia.com/mig-1g.5gb.engines.jpeg: "0"
      nvidia.com/mig-1g.5gb.engines.ofa: "0"
      nvidia.com/mig-1g.5gb.memory: "4864"
      nvidia.com/mig-1g.5gb.multiprocessors: "14"
      nvidia.com/mig-1g.5gb.product: NVIDIA-A100-SXM4-40GB-MIG-1g.5gb
      nvidia.com/mig-1g.5gb.replicas: "1"
      nvidia.com/mig-1g.5gb.sharing-strategy: none
      nvidia.com/mig-1g.5gb.slices.ci: "1"
      nvidia.com/mig-1g.5gb.slices.gi: "1"
      nvidia.com/mig-2g.10gb.count: "1"
      nvidia.com/mig-2g.10gb.engines.copy: "2"
      nvidia.com/mig-2g.10gb.engines.decoder: "1"
      nvidia.com/mig-2g.10gb.engines.encoder: "0"
      nvidia.com/mig-2g.10gb.engines.jpeg: "0"
      nvidia.com/mig-2g.10gb.engines.ofa: "0"
      nvidia.com/mig-2g.10gb.memory: "9984"
      nvidia.com/mig-2g.10gb.multiprocessors: "28"
      nvidia.com/mig-2g.10gb.product: NVIDIA-A100-SXM4-40GB-MIG-2g.10gb
      nvidia.com/mig-2g.10gb.replicas: "1"
      nvidia.com/mig-2g.10gb.sharing-strategy: none
      nvidia.com/mig-2g.10gb.slices.ci: "2"
      nvidia.com/mig-2g.10gb.slices.gi: "2"
      nvidia.com/mig-3g.20gb.count: "1"
      nvidia.com/mig-3g.20gb.engines.copy: "3"
      nvidia.com/mig-3g.20gb.engines.decoder: "2"
      nvidia.com/mig-3g.20gb.engines.encoder: "0"
      nvidia.com/mig-3g.20gb.engines.jpeg: "0"
      nvidia.com/mig-3g.20gb.engines.ofa: "0"
      nvidia.com/mig-3g.20gb.memory: "20096"
      nvidia.com/mig-3g.20gb.multiprocessors: "42"
      nvidia.com/mig-3g.20gb.product: NVIDIA-A100-SXM4-40GB-MIG-3g.20gb
      nvidia.com/mig-3g.20gb.replicas: "1"
      nvidia.com/mig-3g.20gb.sharing-strategy: none
      nvidia.com/mig-3g.20gb.slices.ci: "3"
      nvidia.com/mig-3g.20gb.slices.gi: "3"
      nvidia.com/mig.capable: "true"
      nvidia.com/mig.config: all-balanced
      nvidia.com/mig.config.state: success
      nvidia.com/mig.strategy: mixed
      nvidia.com/mps.capable: "false"
      nvidia.com/vgpu.present: "false"
    name: ai-lab-a100-2
    resourceVersion: "103329"
    uid: c3b97e0b-bdd8-413c-8ade-531cc0709a18
  spec:
    podCIDR: 10.42.1.0/24
    podCIDRs:
    - 10.42.1.0/24
    providerID: k3s://ai-lab-a100-2
  status:
    addresses:
    - address: 10.146.0.55
      type: InternalIP
    - address: ai-lab-a100-2
      type: Hostname
    allocatable:
      cpu: "12"
      ephemeral-storage: "492986995735"
      hugepages-1Gi: "0"
      hugepages-2Mi: "0"
      memory: 87516156Ki
      pods: "110"
    capacity:
      cpu: "12"
      ephemeral-storage: 506771172Ki
      hugepages-1Gi: "0"
      hugepages-2Mi: "0"
      memory: 87516156Ki
      pods: "110"
    conditions:
    - lastHeartbeatTime: "2026-04-24T06:11:49Z"
      lastTransitionTime: "2026-04-23T08:33:09Z"
      message: kubelet has sufficient memory available
      reason: KubeletHasSufficientMemory
      status: "False"
      type: MemoryPressure
    - lastHeartbeatTime: "2026-04-24T06:11:49Z"
      lastTransitionTime: "2026-04-23T08:33:09Z"
      message: kubelet has no disk pressure
      reason: KubeletHasNoDiskPressure
      status: "False"
      type: DiskPressure
    - lastHeartbeatTime: "2026-04-24T06:11:49Z"
      lastTransitionTime: "2026-04-23T08:33:09Z"
      message: kubelet has sufficient PID available
      reason: KubeletHasSufficientPID
      status: "False"
      type: PIDPressure
    - lastHeartbeatTime: "2026-04-24T06:11:49Z"
      lastTransitionTime: "2026-04-23T08:33:09Z"
      message: kubelet is posting ready status
      reason: KubeletReady
      status: "True"
      type: Ready
    daemonEndpoints:
      kubeletEndpoint:
        Port: 10250
    features:
      supplementalGroupsPolicy: true
    images:
    - names:
      - docker.io/grafana/grafana@sha256:0f86bada30d65ef9d0183b90c1e2682ac92d53d95da8bed322b984ea78a4a73a
      - docker.io/grafana/grafana:13.0.1
      sizeBytes: 346938629
    - names:
      - quay.io/prometheus/prometheus@sha256:cd37346c974517be59bd528c43cfff51727fb75393df0ad8d10ce10013a047b6
      - quay.io/prometheus/prometheus:v3.11.2
      sizeBytes: 152918965
    - names:
      - nvcr.io/nvidia/gpu-operator@sha256:64ef3dafb9dd28eebe645010e9a5df1efccddea8ad2d61bb6e0a0c4e12eea310
      - nvcr.io/nvidia/gpu-operator:v26.3.0
      sizeBytes: 138212965
    - names:
      - nvcr.io/nvidia/k8s-dra-driver-gpu@sha256:10d979b1cd3cef492055021a153321fd5636a71771593d96a36a793753911b70
      - nvcr.io/nvidia/k8s-dra-driver-gpu:v25.12.0
      sizeBytes: 96219386
    - names:
      - registry.k8s.io/nfd/node-feature-discovery@sha256:f9ef2ebee55141a1758d3c0a87bb701f5db2adf6856f7218b11bc2bac7b63862
      - registry.k8s.io/nfd/node-feature-discovery:v0.18.3
      sizeBytes: 83817218
    - names:
      - docker.io/rancher/klipper-helm@sha256:2d6c98a07cae39f1bd3bc8405b1b26aff3291b934569cd8dc0c974ba0f356dba
      - docker.io/rancher/klipper-helm:v0.9.14-build20260210
      sizeBytes: 64135089
    - names:
      - nvcr.io/nvidia/k8s/dcgm-exporter@sha256:b5d8813707469c5717ce27a5fefb933a29e8ba6cd2fd7d93ad3dcd6ae18579ef
      - nvcr.io/nvidia/k8s/dcgm-exporter:4.5.1-4.8.0-distroless
      sizeBytes: 59967374
    - names:
      - nvcr.io/nvidia/k8s/container-toolkit@sha256:62204e9fc0f817e6e3fd8edc18d0322feda3728cdf89270d20a8d01d7ef0edb5
      - nvcr.io/nvidia/k8s/container-toolkit:v1.19.0
      sizeBytes: 57183469
    - names:
      - nvcr.io/nvidia/k8s-device-plugin@sha256:75eff5962176618e486da18d73eae57870369b69f186fc8d193973166d1cfad9
      - nvcr.io/nvidia/k8s-device-plugin:v0.19.0
      sizeBytes: 55900878
    - names:
      - docker.io/rancher/mirrored-library-traefik@sha256:9004e1cd1e33c5eb0b6ec02bc6cfda61fe9caca36751114b1c9c6662f01b264a
      - docker.io/rancher/mirrored-library-traefik:3.6.9
      sizeBytes: 52411428
    - names:
      - quay.io/prometheus/alertmanager@sha256:58e117eabccebbff04e6643a3432d6315a2cc3a8c24ab5849bc628886bf08857
      - quay.io/prometheus/alertmanager:v0.32.0
      sizeBytes: 36168424
    - names:
      - nvcr.io/nvidia/cloud-native/k8s-mig-manager@sha256:2efec3ae4208909d18166811254538b6f6996d6bb1d0b524139429fb79c03c70
      - nvcr.io/nvidia/cloud-native/k8s-mig-manager:v0.14.0
      sizeBytes: 35865056
    - names:
      - quay.io/kiwigrid/k8s-sidecar@sha256:a6c101156d42ef1050c536fcbcc03bf314544a63ee2daafe45280bc8dbab398f
      - quay.io/kiwigrid/k8s-sidecar:2.6.0
      sizeBytes: 28447277
    - names:
      - docker.io/rancher/mirrored-coredns-coredns@sha256:82b57287b29beb757c740dbbe68f2d4723da94715b563fffad5c13438b71b14a
      - docker.io/rancher/mirrored-coredns-coredns:1.14.1
      sizeBytes: 23451225
    - names:
      - docker.io/rancher/mirrored-metrics-server@sha256:b2d2efaf5ac3b366ed0f839d2412a2c4279d4fc2a2a733f12c52133faed36c41
      - docker.io/rancher/mirrored-metrics-server:v0.8.1
      sizeBytes: 22550016
    - names:
      - docker.io/rancher/local-path-provisioner@sha256:6ff68ebe98bc623b45ad22c28be84f8a08214982710f3247d5862e9bccce73ef
      - docker.io/rancher/local-path-provisioner:v0.0.34
      sizeBytes: 21600592
    - names:
      - registry.k8s.io/kube-state-metrics/kube-state-metrics@sha256:1545919b72e3ae035454fc054131e8d0f14b42ef6fc5b2ad5c751cafa6b2130e
      - registry.k8s.io/kube-state-metrics/kube-state-metrics:v2.18.0
      sizeBytes: 19306162
    - names:
      - quay.io/prometheus-operator/prometheus-operator@sha256:52a6a92d915ea2fa94314748d99db7a94922e3fe63274f6182fc033b9126b573
      - quay.io/prometheus-operator/prometheus-operator:v0.90.1
      sizeBytes: 19175718
    - names:
      - quay.io/prometheus-operator/prometheus-config-reloader@sha256:693faa0b87243cddca2cffb13586e4e2778b0cdf319cb2e601ba7af3fd19ef7d
      - quay.io/prometheus-operator/prometheus-config-reloader:v0.90.1
      sizeBytes: 14230502
    - names:
      - quay.io/prometheus/node-exporter@sha256:0f422f62c15f154af8d8572b23d623aebfb10cec73a5c654d18f911f3f9df241
      - quay.io/prometheus/node-exporter:v1.11.1
      sizeBytes: 13308798
    - names:
      - ghcr.io/jkroepke/kube-webhook-certgen@sha256:4f6da0256b1bd263baf86ab990a65740118ea3feaaa453e4e752a4bf42f0de6c
      - ghcr.io/jkroepke/kube-webhook-certgen:1.8.1
      sizeBytes: 12948114
    - names:
      - docker.io/rancher/klipper-lb@sha256:f377e04abff8fd78f110f2cc9acb564655c7e84d70166c808875cd49505735c1
      - docker.io/rancher/klipper-lb:v0.4.14
      sizeBytes: 5469847
    - names:
      - docker.io/library/busybox@sha256:1487d0af5f52b4ba31c7e465126ee2123fe3f2305d638e7827681e7cf6c83d5e
      - docker.io/library/busybox:1.37.0
      - docker.io/library/busybox:latest
      sizeBytes: 2222002
    - names:
      - docker.io/rancher/mirrored-library-busybox@sha256:101b4afd76732482eff9b95cae5f94bcf295e521fbec4e01b69c5421f3f3f3e5
      - docker.io/rancher/mirrored-library-busybox:1.37.0
      sizeBytes: 2151353
    - names:
      - docker.io/rancher/mirrored-pause@sha256:74c4244427b7312c5b901fe0f67cbc53683d06f4f24c6faee65d4182bf0fa893
      - docker.io/rancher/mirrored-pause:3.6
      sizeBytes: 301463
    nodeInfo:
      architecture: amd64
      bootID: f972eb4c-ebbb-4026-9afb-ac9ab0e1c04a
      containerRuntimeVersion: containerd://2.1.5-k3s1
      kernelVersion: 6.17.0-1012-gcp
      kubeProxyVersion: ""
      kubeletVersion: v1.35.2+k3s1
      machineID: 9ab6492c7d2c4093aa8aa22324b1b555
      operatingSystem: linux
      osImage: Ubuntu 24.04.4 LTS
      systemUUID: eb6bb6cc-8eda-954c-5079-bc86ccba442b
    runtimeHandlers:
    - features:
        recursiveReadOnlyMounts: true
        userNamespaces: true
      name: ""
    - features:
        recursiveReadOnlyMounts: true
        userNamespaces: true
      name: nvidia
    - features:
        recursiveReadOnlyMounts: true
        userNamespaces: true
      name: nvidia-cdi
    - features:
        recursiveReadOnlyMounts: true
        userNamespaces: true
      name: runc
    - features:
        recursiveReadOnlyMounts: false
        userNamespaces: false
      name: runhcs-wcow-process
kind: List
metadata:
  resourceVersion: ""
