{
 "title": "NVIDIA DCGM Dashboard for Kubernetes (MIG)",
 "description": "This Grafana dashboard uses the NVIDIA DCGM exporter to monitor GPU performance in Kubernetes clusters. Supporting both MIG and non-MIG GPUs, it provides real-time metrics on utilization, memory, temperature, power, and more, enabling efficient management of NVIDIA GPU resources.",
 "tags": [
  "gpu",
  "kubernetes-mixin",
  "MIG"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "auto",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "Hostname",
    "query": {
     "query": "label_values(DCGM_FI_DEV_FB_FREE,Hostname)"
    }
   },
   {
    "name": "gpu",
    "label": "GPU ID",
    "query": {
     "query": "label_values(DCGM_FI_DEV_FB_FREE,gpu)"
    }
   },
   {
    "name": "mig",
    "label": "MIG Profile",
    "query": {
     "query": "label_values(DCGM_FI_DEV_FB_FREE,GPU_I_PROFILE)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Partitions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total GPU Engine Utilization",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * avg (DCGM_FI_PROF_GR_ENGINE_ACTIVE{Hostname=~\"$Hostname\", gpu=~\"$gpu\", GPU_I_PROFILE=~\"$mig\"})\n"
    }
   ]
  },
  {
   "title": "Tensor Utilization",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * avg (DCGM_FI_PROF_PIPE_TENSOR_ACTIVE{Hostname=~\"$Hostname\", gpu=~\"$gpu\", GPU_I_PROFILE=~\"$mig\"})\n"
    }
   ]
  },
  {
   "title": "GPU Memory Bandwidth",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100* avg (DCGM_FI_PROF_DRAM_ACTIVE{Hostname=~\"$Hostname\", gpu=~\"$gpu\", GPU_I_PROFILE=~\"$mig\"})\n"
    }
   ]
  },
  {
   "title": "GPU Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (DCGM_FI_DEV_FB_USED{Hostname=~\"$Hostname\", gpu=~\"$gpu\", GPU_I_PROFILE=~\"$mig\"})\n"
    },
    {
     "expr": "sum (DCGM_FI_DEV_FB_USED{Hostname=~\"$Hostname\", gpu=~\"$gpu\", GPU_I_PROFILE=~\"$mig\"}) + sum (DCGM_FI_DEV_FB_FREE{Hostname=~\"$Hostname\", gpu=~\"$gpu\", GPU_I_PROFILE=~\"$mig\"})",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "GPU Engine Utilization",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * DCGM_FI_PROF_GR_ENGINE_ACTIVE{Hostname=~\"$Hostname\", gpu=~\"$gpu\"}",
     "legendFormat": "{{GPU_I_PROFILE}} - ID {{GPU_I_ID}}"
    }
   ]
  },
  {
   "title": "Others",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 },
   "collapsed": true
  },
  {
   "title": "GPU temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "avg by(Hostname, gpu) (DCGM_FI_DEV_GPU_TEMP{Hostname=~\"$Hostname\", gpu=~\"$gpu\"})",
     "legendFormat": "Node:{{Hostname}}  GPU:{{gpu}}"
    }
   ]
  },
  {
   "title": "Power Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 20, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "avg by(Hostname, gpu) (DCGM_FI_DEV_POWER_USAGE{Hostname=~\"$Hostname\", gpu=~\"$gpu\"})",
     "legendFormat": "Node:{{Hostname}}  GPU:{{gpu}}"
    }
   ]
  },
  {
   "title": "GPU Energy Draw Total",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "expr": "sum(increase(DCGM_FI_DEV_TOTAL_ENERGY_CONSUMPTION{Hostname=~\"$Hostname\", gpu=~\"$gpu\"}[1h]) / 3600000)",
     "legendFormat": "Last 1h"
    },
    {
     "expr": "sum(increase(DCGM_FI_DEV_TOTAL_ENERGY_CONSUMPTION{Hostname=~\"$Hostname\", gpu=~\"$gpu\"}[24h]) / 3600000)",
     "legendFormat": "Last 24h"
    }
   ]
  },
  {
   "title": "SM clock",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "rotmhz" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(modelName) (DCGM_FI_DEV_SM_CLOCK{Hostname=~\"$Hostname\", gpu=~\"$gpu\"})",
     "legendFormat": "{{modelName}}"
    }
   ]
  },
  {
   "title": "Memory clock",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "rotmhz" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(modelName) (DCGM_FI_DEV_MEM_CLOCK{Hostname=~\"$Hostname\", gpu=~\"$gpu\"})",
     "legendFormat": "Node:{{Hostname}}  GPU:{{gpu}}"
    }
   ]
  },
  {
   "title": "Memory temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "avg by(Hostname, gpu) (DCGM_FI_DEV_MEMORY_TEMP{Hostname=~\"$Hostname\", gpu=~\"$gpu\"})",
     "legendFormat": "Node:{{Hostname}}  GPU:{{gpu}}"
    }
   ]
  },
  {
   "title": "NVLink bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "avg by(Hostname, gpu) (rate(DCGM_FI_DEV_NVLINK_BANDWIDTH_TOTAL{Hostname=~\"$Hostname\", gpu=~\"$gpu\"}[$__rate_interval]))",
     "legendFormat": "Node:{{Hostname}}  GPU:{{gpu}}"
    }
   ]
  },
  {
   "title": "Instance type",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 58 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by(modelName) (DCGM_FI_DEV_SM_CLOCK)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "GPU Util", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "avg by(GPU_I_ID, Hostname, gpu, GPU_I_PROFILE) (DCGM_FI_DEV_FB_USED{Hostname=~\"$Hostname\", gpu=~\"$gpu\", GPU_I_PROFILE=~\"$mig\"})",
     "legendFormat": "[{{Hostname}}] - {{gpu}}/{{GPU_I_ID}} - {{GPU_I_PROFILE}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(GPU_I_ID, Hostname, gpu, GPU_I_PROFILE) (DCGM_FI_DEV_FB_USED{Hostname=~\"$Hostname\", gpu=~\"$gpu\", GPU_I_PROFILE=~\"$mig\"})",
     "legendFormat": "[{{Hostname}}] - {{gpu}}/{{GPU_I_ID}} - {{GPU_I_PROFILE}}"
    }
   ]
  },
  {
   "title": "Partitioned GPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 20, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg by(GPU_I_ID, Hostname, gpu, GPU_I_PROFILE) (DCGM_FI_PROF_GR_ENGINE_ACTIVE{Hostname=~\"$Hostname\", gpu=~\"$gpu\", GPU_I_PROFILE=~\"$mig\"})",
     "legendFormat": "[{{Hostname}}] - {{gpu}}/{{GPU_I_ID}} - {{GPU_I_PROFILE}}"
    }
   ]
  },
  {
   "title": "Tensor Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg by(GPU_I_ID, Hostname, gpu, GPU_I_PROFILE) (DCGM_FI_PROF_PIPE_TENSOR_ACTIVE{Hostname=~\"$Hostname\", gpu=~\"$gpu\", GPU_I_PROFILE=~\"$mig\"})",
     "legendFormat": "[{{Hostname}}] - {{gpu}}/{{GPU_I_ID}} - {{GPU_I_PROFILE}}"
    }
   ]
  },
  {
   "title": "Memory Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg by(GPU_I_ID, Hostname, gpu, GPU_I_PROFILE) (DCGM_FI_PROF_DRAM_ACTIVE{Hostname=~\"$Hostname\", gpu=~\"$gpu\", GPU_I_PROFILE=~\"$mig\"})",
     "legendFormat": "[{{Hostname}}] - {{gpu}}/{{GPU_I_ID}} - {{GPU_I_PROFILE}}"
    }
   ]
  },
  {
   "title": "Total GPU Engine Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 20, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg(DCGM_FI_PROF_GR_ENGINE_ACTIVE{Hostname=~\"$Hostname\", gpu=~\"$gpu\", GPU_I_PROFILE=~\"$mig\"})",
     "legendFormat": "Node:{{Hostname}}  GPU:{{gpu}}"
    }
   ]
  },
  {
   "title": "Allocation Table",
   "type": "table",
   "gridPos": { "h": 10, "w": 16, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "count by(Hostname, gpu, GPU_I_PROFILE, GPU_I_ID, exported_namespace, exported_pod) (DCGM_FI_DEV_SM_CLOCK)",
     "legendFormat": "{{ GPU }}"
    }
   ]
  },
  { "title": "Error", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 76 } },
  {
   "title": "PCIe retry rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 77 },
   "targets": [
    {
     "expr": "avg by(Hostname, gpu) (rate(DCGM_FI_DEV_PCIE_REPLAY_COUNTER{Hostname=~\"$Hostname\", gpu=~\"$gpu\"}[$__rate_interval]))",
     "legendFormat": "Node:{{Hostname}}  GPU:{{gpu}}"
    }
   ]
  },
  {
   "title": "XID error",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 77 },
   "targets": [
    {
     "expr": "avg by(Hostname, gpu) (DCGM_FI_DEV_XID_ERRORS{Hostname=~\"$Hostname\", gpu=~\"$gpu\"})",
     "legendFormat": "Node:{{Hostname}}  GPU:{{gpu}}"
    }
   ]
  }
 ]
}