apiVersion: v1
items:
- apiVersion: resource.k8s.io/v1
  kind: ResourceSlice
  metadata:
    creationTimestamp: "2026-04-23T09:52:47Z"
    generateName: ai-lab-a100-2-compute-domain.nvidia.com-
    generation: 5
    name: ai-lab-a100-2-compute-domain.nvidia.com-q6fmw
    ownerReferences:
    - apiVersion: v1
      controller: true
      kind: Node
      name: ai-lab-a100-2
      uid: c3b97e0b-bdd8-413c-8ade-531cc0709a18
    resourceVersion: "551818"
    uid: fad23929-1d15-4a54-a432-5314b9686238
  spec:
    devices:
    - attributes:
        id:
          int: 0
        type:
          string: daemon
      name: daemon-0
    - attributes:
        id:
          int: 0
        type:
          string: channel
      name: channel-0
    driver: compute-domain.nvidia.com
    nodeName: ai-lab-a100-2
    pool:
      generation: 1
      name: ai-lab-a100-2
      resourceSliceCount: 1
- apiVersion: resource.k8s.io/v1
  kind: ResourceSlice
  metadata:
    creationTimestamp: "2026-04-23T09:52:47Z"
    generateName: ai-lab-a100-2-gpu.nvidia.com-
    generation: 8
    name: ai-lab-a100-2-gpu.nvidia.com-phhqr
    ownerReferences:
    - apiVersion: v1
      controller: true
      kind: Node
      name: ai-lab-a100-2
      uid: c3b97e0b-bdd8-413c-8ade-531cc0709a18
    resourceVersion: "555571"
    uid: 30250f1b-b6c6-48c5-b4d7-5f52a909a93b
  spec:
    devices:
    - attributes:
        addressingMode:
          string: None
        architecture:
          string: Ampere
        brand:
          string: Nvidia
        cudaComputeCapability:
          version: 8.0.0
        cudaDriverVersion:
          version: 13.1.0
        driverVersion:
          version: 590.48.1
        parentUUID:
          string: GPU-8fb50131-6654-9551-735c-932a7c87f13c
        productName:
          string: NVIDIA A100-SXM4-40GB
        profile:
          string: 2g.10gb
        resource.kubernetes.io/pciBusID:
          string: "0000:00:04.0"
        resource.kubernetes.io/pcieRoot:
          string: pci0000:00
        type:
          string: mig
        uuid:
          string: MIG-12054703-aabd-5b77-bb10-d91e2c481bec
      capacity:
        copyEngines:
          value: "2"
        decoders:
          value: "1"
        encoders:
          value: "0"
        jpegEngines:
          value: "0"
        memory:
          value: 9984Mi
        memorySlice2:
          value: "1"
        memorySlice3:
          value: "1"
        multiprocessors:
          value: "28"
        ofaEngines:
          value: "0"
      name: gpu-0-mig-2g10gb-14-2
    - attributes:
        addressingMode:
          string: None
        architecture:
          string: Ampere
        brand:
          string: Nvidia
        cudaComputeCapability:
          version: 8.0.0
        cudaDriverVersion:
          version: 13.1.0
        driverVersion:
          version: 590.48.1
        parentUUID:
          string: GPU-8fb50131-6654-9551-735c-932a7c87f13c
        productName:
          string: NVIDIA A100-SXM4-40GB
        profile:
          string: 2g.10gb
        resource.kubernetes.io/pciBusID:
          string: "0000:00:04.0"
        resource.kubernetes.io/pcieRoot:
          string: pci0000:00
        type:
          string: mig
        uuid:
          string: MIG-443d8c24-3028-5448-bdae-9105f6f73fb6
      capacity:
        copyEngines:
          value: "2"
        decoders:
          value: "1"
        encoders:
          value: "0"
        jpegEngines:
          value: "0"
        memory:
          value: 9984Mi
        memorySlice4:
          value: "1"
        memorySlice5:
          value: "1"
        multiprocessors:
          value: "28"
        ofaEngines:
          value: "0"
      name: gpu-0-mig-2g10gb-14-4
    - attributes:
        addressingMode:
          string: None
        architecture:
          string: Ampere
        brand:
          string: Nvidia
        cudaComputeCapability:
          version: 8.0.0
        cudaDriverVersion:
          version: 13.1.0
        driverVersion:
          version: 590.48.1
        parentUUID:
          string: GPU-8fb50131-6654-9551-735c-932a7c87f13c
        productName:
          string: NVIDIA A100-SXM4-40GB
        profile:
          string: 1g.10gb
        resource.kubernetes.io/pciBusID:
          string: "0000:00:04.0"
        resource.kubernetes.io/pcieRoot:
          string: pci0000:00
        type:
          string: mig
        uuid:
          string: MIG-e0930d26-0b29-5fd4-9d3b-7597d0228fa7
      capacity:
        copyEngines:
          value: "1"
        decoders:
          value: "1"
        encoders:
          value: "0"
        jpegEngines:
          value: "0"
        memory:
          value: 9984Mi
        memorySlice6:
          value: "1"
        memorySlice7:
          value: "1"
        multiprocessors:
          value: "14"
        ofaEngines:
          value: "0"
      name: gpu-0-mig-1g10gb-15-6
    - attributes:
        addressingMode:
          string: None
        architecture:
          string: Ampere
        brand:
          string: Nvidia
        cudaComputeCapability:
          version: 8.0.0
        cudaDriverVersion:
          version: 13.1.0
        driverVersion:
          version: 590.48.1
        parentUUID:
          string: GPU-8fb50131-6654-9551-735c-932a7c87f13c
        productName:
          string: NVIDIA A100-SXM4-40GB
        profile:
          string: 2g.10gb
        resource.kubernetes.io/pciBusID:
          string: "0000:00:04.0"
        resource.kubernetes.io/pcieRoot:
          string: pci0000:00
        type:
          string: mig
        uuid:
          string: MIG-9925948d-7021-552f-926f-7b17c06e570b
      capacity:
        copyEngines:
          value: "2"
        decoders:
          value: "1"
        encoders:
          value: "0"
        jpegEngines:
          value: "0"
        memory:
          value: 9984Mi
        memorySlice0:
          value: "1"
        memorySlice1:
          value: "1"
        multiprocessors:
          value: "28"
        ofaEngines:
          value: "0"
      name: gpu-0-mig-2g10gb-14-0
    driver: gpu.nvidia.com
    nodeName: ai-lab-a100-2
    pool:
      generation: 1
      name: ai-lab-a100-2
      resourceSliceCount: 1
kind: List
metadata:
  resourceVersion: ""
