apiVersion: apps/v1
kind: Deployment
metadata:
  name: ollama-mig
  namespace: ollama-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ollama-mig
  template:
    metadata:
      labels:
        app: ollama-mig
    spec:
      initContainers:
      - name: ollama-pull
        image: ollama/ollama:0.12.11-rc1
        command: ["/bin/sh", "-c"]
        args:
          - |
            ollama serve &
            sleep 5
            ollama pull tinyllama
        volumeMounts:
        - name: ollama-data
          mountPath: /root/.ollama

      containers:
      - name: ollama
        image: ollama/ollama:0.12.11-rc1
        ports:
        - containerPort: 11434

        env:
        - name: OLLAMA_HOST
          value: "0.0.0.0:11434"

        resources:
          claims:
          - name: mig-gpu

        volumeMounts:
        - name: ollama-data
          mountPath: /root/.ollama

      resourceClaims:
      - name: mig-gpu
        resourceClaimTemplateName: whatever-small-mig

      volumes:
      - name: ollama-data
        emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: ollama-nodeport
  namespace: ollama-test
spec:
  type: NodePort
  selector:
    app: ollama-mig
  ports:
  - port: 11434
    targetPort: 11434
    nodePort: 31134