apiVersion: resource.k8s.io/v1
kind: DeviceClass
metadata:
  name: small-gpu
spec:
  selectors:
    - cel:
        expression: device.driver == 'gpu.nvidia.com' &&
          device.attributes["gpu.nvidia.com"].profile == "1g.5gb"
