apiVersion: batch/v1
kind: Job
metadata:
  name: sample-dra-job-1
  namespace: experiment
  labels:
    kueue.x-k8s.io/queue-name: baseline-medium-uq
    kueue.x-k8s.io/priority-class: gold-priority
spec:
  template:
    spec:
      containers:
        - name: dummy-job
          image: nvidia/cuda:12.8.2-base-ubuntu24.04
          args: ["bash", "-c", "nvidia-smi; sleep 10"]
          resources:
            claims:
              - name: gpu
      resourceClaims:
        - name: gpu
          resourceClaimTemplateName: claim-medium
      restartPolicy: Never

---
apiVersion: batch/v1
kind: Job
metadata:
  name: sample-dra-job-2
  namespace: experiment
  labels:
    kueue.x-k8s.io/queue-name: baseline-medium-uq
    kueue.x-k8s.io/priority-class: bronze-priority
spec:
  template:
    spec:
      containers:
        - name: dummy-job
          image: nvidia/cuda:12.8.2-base-ubuntu24.04
          args: ["bash", "-c", "nvidia-smi; sleep 10"]
          resources:
            claims:
              - name: gpu
      resourceClaims:
        - name: gpu
          resourceClaimTemplateName: claim-medium
      restartPolicy: Never

---
apiVersion: batch/v1
kind: Job
metadata:
  name: sample-dra-job-3
  namespace: experiment
  labels:
    kueue.x-k8s.io/queue-name: baseline-medium-uq
    kueue.x-k8s.io/priority-class: bronze-priority
spec:
  template:
    spec:
      containers:
        - name: dummy-job
          image: nvidia/cuda:12.8.2-base-ubuntu24.04
          args: ["bash", "-c", "nvidia-smi; sleep 10"]
          resources:
            claims:
              - name: gpu
      resourceClaims:
        - name: gpu
          resourceClaimTemplateName: claim-medium
      restartPolicy: Never

---
apiVersion: batch/v1
kind: Job
metadata:
  name: sample-dra-job-4
  namespace: experiment
  labels:
    kueue.x-k8s.io/queue-name: baseline-medium-uq
    kueue.x-k8s.io/priority-class: bronze-priority
spec:
  template:
    spec:
      containers:
        - name: dummy-job
          image: nvidia/cuda:12.8.2-base-ubuntu24.04
          args: ["bash", "-c", "nvidia-smi; sleep 10"]
          resources:
            claims:
              - name: gpu
      resourceClaims:
        - name: gpu
          resourceClaimTemplateName: claim-medium
      restartPolicy: Never

---
apiVersion: batch/v1
kind: Job
metadata:
  name: sample-dra-job-5
  namespace: experiment
  labels:
    kueue.x-k8s.io/queue-name: baseline-medium-uq
    kueue.x-k8s.io/priority-class: gold-priority
spec:
  template:
    spec:
      containers:
        - name: dummy-job
          image: nvidia/cuda:12.8.2-base-ubuntu24.04
          args: ["bash", "-c", "nvidia-smi; sleep 10"]
          resources:
            claims:
              - name: gpu
      resourceClaims:
        - name: gpu
          resourceClaimTemplateName: claim-medium
      restartPolicy: Never
